### ISSUE TITLE
Oxygen Not Included Crash using Better Info Cards and Thermal Tool Tips

### ISSUE THREAD

**Issue by Crazz2424** [AzeTheGreat/ONI-Mods#17] opened 2021-09-19 20:38 UTC
Check that you have the latest version of the mod. I recommend using Mod Updater to do so. Only continue if you are using the latest mod release. **I do have the latest version**

If the mod is crashing, upload your Player Log. Make sure that you upload the player log directly after the crash, before launching the game again. **Uploaded**

If something is not behaving as expected, please describe it in detail. Describe what you expect to happen, what is actually happening in game, and how they differ. **I only have had this crash twice in many hours of play, the first time (which I did not have a log for) was a few months ago. This time, unrelated to the last time, happened when I was clicking on a pipe or bridge pipe that I was selecting to deconstruct. I received a message saying the following which had both Better Info Cards and Thermal Tool Tips selected.**

Do note that I am playing with the DLC purchased but not active. I'm using the Cosmic Calling Update.

KeyNotFoundException: The given key was not present in the dictionary.

System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <695d1cc93cca45069c528c15c9fdd749>:0)
BetterInfoCards.TextInfo`1+<>c__DisplayClass11_0[T].<GetSplitByRange>g__GetTIValue|4 (BetterInfoCards.InfoCard ic) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.TextInfo`1+<>c__DisplayClass11_0[T].<GetSplitByRange>b__0 (BetterInfoCards.InfoCard x) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
System.Linq.Enumerable+SelectListIterator`2[TSource,TResult].MoveNext () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Collections.Generic.EnumerableHelpers.ToArray[T] (System.Collections.Generic.IEnumerable`1[T] source, System.Int32& length) (at <aa976c2104104b7ca9e1785715722c9d>:0)
System.Collections.Generic.SortedSet`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection, System.Collections.Generic.IComparer`1[T] comparer) (at <aa976c2104104b7ca9e1785715722c9d>:0)
System.Collections.Generic.SortedSet`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) (at <aa976c2104104b7ca9e1785715722c9d>:0)
BetterInfoCards.TextInfo`1[T].GetSplitByRange (System.Collections.Generic.List`1[T] cards, System.ValueTuple`2[T1,T2] def) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.TextInfo`1[T].<SplitByTIDefs>b__10_0 (System.Collections.Generic.List`1[T] g, System.ValueTuple`2[T1,T2] def) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters+<>c__DisplayClass3_1`2[TVal,TSplit].<SplitBySplitters>b__0 (System.Collections.Generic.List`1[T] x) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters.SplitMany[T] (System.Collections.Generic.List`1[T] source, System.Func`2[T,TResult] getSplits) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters.SplitBySplitters[TVal,TSplit] (System.Collections.Generic.List`1[T] source, System.Collections.Generic.List`1[T] splitters, System.Func`3[T1,T2,TResult] getSplits) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.TextInfo`1[T].SplitByTIDefs (System.Collections.Generic.List`1[T] cards) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.DisplayCards+<>c.<UpdateData>b__0_5 (System.Collections.Generic.List`1[T] group, System.Collections.Generic.KeyValuePair`2[TKey,TValue] ti) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters+<>c__DisplayClass3_1`2[TVal,TSplit].<SplitBySplitters>b__0 (System.Collections.Generic.List`1[T] x) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters.SplitMany[T] (System.Collections.Generic.List`1[T] source, System.Func`2[T,TResult] getSplits) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters.SplitBySplitters[TVal,TSplit] (System.Collections.Generic.List`1[T] source, System.Collections.Generic.List`1[T] splitters, System.Func`3[T1,T2,TResult] getSplits) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.DisplayCards+<>c.<UpdateData>b__0_2 (System.Collections.Generic.List`1[T] cards) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters.SplitMany[T] (System.Collections.Generic.List`1[T] source, System.Func`2[T,TResult] getSplits) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.DisplayCards.UpdateData (System.Collections.Generic.List`1[T] infoCards) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.CollectHoverInfo+EditWidgets_Patch.Postfix () (at <dd388658d32648499f7b667f9fd7f3f8>:0)
(wrapper dynamic-method) HoverTextDrawer.HoverTextDrawer.EndDrawing_Patch1(HoverTextDrawer)
(wrapper dynamic-method) SelectToolHoverTextCard.SelectToolHoverTextCard.UpdateHoverElements_Patch0(SelectToolHoverTextCard,System.Collections.Generic.List`1<KSelectable>)
InterfaceTool.UpdateHoverElements (System.Collections.Generic.List`1[T] hits) (at <e29f62b80c9e4a9da170d249305d6eb7>:0)
InterfaceTool.LateUpdate () (at <e29f62b80c9e4a9da170d249305d6eb7>:0)

Build: U35-479045-V

[Player.log](https://github.com/AzeTheGreat/ONI-Mods/files/7192883/Player.log)
If the issue occurs consistently, please include details on the steps or circumstances required to reproduce it.

**Comment by HugePinball** [comment] 2021-10-30 14:41
I've gotten a similar crash as above a number of times.  In addition to Better Info Cards and Thermal Tool Tips, the mod Notepad ( https://steamcommunity.com/sharedfiles/filedetails/?id=1996618130 ) was also highlighted by the game on crash.

`KeyNotFoundException: The given key was not present in the dictionary.

System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <695d1cc93cca45069c528c15c9fdd749>:0)
BetterInfoCards.TextInfo`1+<>c__DisplayClass11_0[T].<GetSplitByRange>g__GetTIValue|4 (BetterInfoCards.InfoCard ic) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.TextInfo`1+<>c__DisplayClass11_0[T].<GetSplitByRange>b__0 (BetterInfoCards.InfoCard x) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
System.Linq.Enumerable+SelectListIterator`2[TSource,TResult].MoveNext () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Collections.Generic.EnumerableHelpers.ToArray[T] (System.Collections.Generic.IEnumerable`1[T] source, System.Int32& length) (at <aa976c2104104b7ca9e1785715722c9d>:0)
System.Collections.Generic.SortedSet`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection, System.Collections.Generic.IComparer`1[T] comparer) (at <aa976c2104104b7ca9e1785715722c9d>:0)
System.Collections.Generic.SortedSet`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) (at <aa976c2104104b7ca9e1785715722c9d>:0)
BetterInfoCards.TextInfo`1[T].GetSplitByRange (System.Collections.Generic.List`1[T] cards, System.ValueTuple`2[T1,T2] def) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.TextInfo`1[T].<SplitByTIDefs>b__10_0 (System.Collections.Generic.List`1[T] g, System.ValueTuple`2[T1,T2] def) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters+<>c__DisplayClass3_1`2[TVal,TSplit].<SplitBySplitters>b__0 (System.Collections.Generic.List`1[T] x) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters.SplitMany[T] (System.Collections.Generic.List`1[T] source, System.Func`2[T,TResult] getSplits) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters.SplitBySplitters[TVal,TSplit] (System.Collections.Generic.List`1[T] source, System.Collections.Generic.List`1[T] splitters, System.Func`3[T1,T2,TResult] getSplits) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.TextInfo`1[T].SplitByTIDefs (System.Collections.Generic.List`1[T] cards) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.DisplayCards+<>c.<UpdateData>b__0_5 (System.Collections.Generic.List`1[T] group, System.Collections.Generic.KeyValuePair`2[TKey,TValue] ti) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters+<>c__DisplayClass3_1`2[TVal,TSplit].<SplitBySplitters>b__0 (System.Collections.Generic.List`1[T] x) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters.SplitMany[T] (System.Collections.Generic.List`1[T] source, System.Func`2[T,TResult] getSplits) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters.SplitBySplitters[TVal,TSplit] (System.Collections.Generic.List`1[T] source, System.Collections.Generic.List`1[T] splitters, System.Func`3[T1,T2,TResult] getSplits) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.DisplayCards+<>c.<UpdateData>b__0_2 (System.Collections.Generic.List`1[T] cards) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters.SplitMany[T] (System.Collections.Generic.List`1[T] source, System.Func`2[T,TResult] getSplits) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.DisplayCards.UpdateData (System.Collections.Generic.List`1[T] infoCards) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.CollectHoverInfo+EditWidgets_Patch.Postfix () (at <dd388658d32648499f7b667f9fd7f3f8>:0)
(wrapper dynamic-method) HoverTextDrawer.HoverTextDrawer.EndDrawing_Patch1(HoverTextDrawer)
(wrapper dynamic-method) SelectToolHoverTextCard.SelectToolHoverTextCard.UpdateHoverElements_Patch1(SelectToolHoverTextCard,System.Collections.Generic.List`1<KSelectable>)
InterfaceTool.UpdateHoverElements (System.Collections.Generic.List`1[T] hits) (at <c8af1c7577924b4e8159a8d1b7565399>:0)
InterfaceTool.LateUpdate () (at <c8af1c7577924b4e8159a8d1b7565399>:0)

Build: U37-484114-S`

[Player.log](https://github.com/AzeTheGreat/ONI-Mods/files/7446863/Player.log)

**Comment by AzeTheGreat** [comment] 2021-10-30 15:04
@HugePinball Can you reproduce the issue?  How frequently does it occur?  Unfortunately I've been completely unable to reproduce these crashes and can't figure out how to fix the issue.

**Comment by Traister101** [comment] 2021-12-31 07:13
Might as well join in as this crash is happening to me _somewhat_ frequently. It's seemingly random as I can often simply re-launch and the crash doesn't happen again. One thing I've noticed is I always have the basic curser no tools but sadly there's no pattern as to what I'm hovering over that I've noticed. The only mod that has ever been highlighted in my experience is Better info cards but I don't have Thermal Tool Tips installed.

Just bought the game (and DLC) a handful of days ago and having a blast but in my nearly 40 hours (don't remember when I installed this but maybe 20 hours in?) I've only experienced around 5 crashes due to whatever is going wrong so it's not that much of a pain. Having better info cards is worth a crash here and there what I really dislike is discovering I should have been asleep a few hours ago :)

Own DLC but not activated 
Mod version: v2021.7.17.2


`KeyNotFoundException: The given key was not present in the dictionary.

System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <695d1cc93cca45069c528c15c9fdd749>:0)
BetterInfoCards.TextInfo`1+<>c__DisplayClass11_0[T].<GetSplitByRange>g__GetTIValue|4 (BetterInfoCards.InfoCard ic) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.TextInfo`1+<>c__DisplayClass11_0[T].<GetSplitByRange>b__0 (BetterInfoCards.InfoCard x) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
System.Linq.Enumerable+SelectListIterator`2[TSource,TResult].MoveNext () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Collections.Generic.EnumerableHelpers.ToArray[T] (System.Collections.Generic.IEnumerable`1[T] source, System.Int32& length) (at <aa976c2104104b7ca9e1785715722c9d>:0)
System.Collections.Generic.SortedSet`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection, System.Collections.Generic.IComparer`1[T] comparer) (at <aa976c2104104b7ca9e1785715722c9d>:0)
System.Collections.Generic.SortedSet`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) (at <aa976c2104104b7ca9e1785715722c9d>:0)
BetterInfoCards.TextInfo`1[T].GetSplitByRange (System.Collections.Generic.List`1[T] cards, System.ValueTuple`2[T1,T2] def) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.TextInfo`1[T].<SplitByTIDefs>b__10_0 (System.Collections.Generic.List`1[T] g, System.ValueTuple`2[T1,T2] def) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters+<>c__DisplayClass3_1`2[TVal,TSplit].<SplitBySplitters>b__0 (System.Collections.Generic.List`1[T] x) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters.SplitMany[T] (System.Collections.Generic.List`1[T] source, System.Func`2[T,TResult] getSplits) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters.SplitBySplitters[TVal,TSplit] (System.Collections.Generic.List`1[T] source, System.Collections.Generic.List`1[T] splitters, System.Func`3[T1,T2,TResult] getSplits) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.TextInfo`1[T].SplitByTIDefs (System.Collections.Generic.List`1[T] cards) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.DisplayCards+<>c.<UpdateData>b__0_5 (System.Collections.Generic.List`1[T] group, System.Collections.Generic.KeyValuePair`2[TKey,TValue] ti) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters+<>c__DisplayClass3_1`2[TVal,TSplit].<SplitBySplitters>b__0 (System.Collections.Generic.List`1[T] x) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters.SplitMany[T] (System.Collections.Generic.List`1[T] source, System.Func`2[T,TResult] getSplits) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters.SplitBySplitters[TVal,TSplit] (System.Collections.Generic.List`1[T] source, System.Collections.Generic.List`1[T] splitters, System.Func`3[T1,T2,TResult] getSplits) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.DisplayCards+<>c.<UpdateData>b__0_2 (System.Collections.Generic.List`1[T] cards) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.Util.Splitters.SplitMany[T] (System.Collections.Generic.List`1[T] source, System.Func`2[T,TResult] getSplits) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.DisplayCards.UpdateData (System.Collections.Generic.List`1[T] infoCards) (at <dd388658d32648499f7b667f9fd7f3f8>:0)
BetterInfoCards.CollectHoverInfo+EditWidgets_Patch.Postfix () (at <dd388658d32648499f7b667f9fd7f3f8>:0)
(wrapper dynamic-method) HoverTextDrawer.HoverTextDrawer.EndDrawing_Patch1(HoverTextDrawer)
(wrapper dynamic-method) SelectToolHoverTextCard.SelectToolHoverTextCard.UpdateHoverElements_Patch0(SelectToolHoverTextCard,System.Collections.Generic.List`1<KSelectable>)
InterfaceTool.UpdateHoverElements (System.Collections.Generic.List`1[T] hits) (at <84ec5be14c67406292956d199a0bec75>:0)
InterfaceTool.LateUpdate () (at <84ec5be14c67406292956d199a0bec75>:0)

Build: U39-490405-V`

**Comment by Traister101** [comment] 2021-12-31 07:55
New comment as I got (poorly edited to not waste your time) video :)

And I forgot to copy the crash log but well it'd probably be the same one as those other two since the crash in the video is 100% what happened those two times. 

Player log from the last crash in the video and the [video itself](https://youtu.be/f_0s8SWpx_0) which again is edited (poorly) mainly to remove loading. So any cuts are just downtime ie game closing, launching, enabling mods, loading in you get the idea. 
[Player.log](https://github.com/AzeTheGreat/ONI-Mods/files/7795605/Player.log)

**Comment by mx2048** [comment] 2022-01-03 09:23
Same bug. I can reproduce. See the image below:
![ONI - Better info - bug -tile below](https://user-images.githubusercontent.com/24634074/147915018-6cf5c84a-7864-4d46-9a72-fc04db79f518.jpg)
Notice the mouse cursor. It hovers over a tile (first tile) with a petroleum drop. The tile (second tile) below the first tile is going to be dug by a dupe. Once it is dug, I hover over the second tile and the tooltip makes a crash.

I think you do not need to reproduce.  The error message "`KeyNotFoundException: The given key was not present in the dictionary.`" Thus, you can just add a simple condition to check if a key is in the dictionary. Or just try-catch.

**Comment by AzeTheGreat** [comment] 2022-03-06 23:42
Thank you all.  I believe this should be fixed in 123a3d6077c4b38be2ba0eee2b8b827410d6d7e1.

Special thanks to @Traister101: your video gave me enough info to reproduce.

@mx2048: Of course, I could just null check and/or catch exceptions.  However, BIC is a very complicated, tightly interwoven piece of code.  This error was a sign of something fundamentally incorrect about the assumptions I had made, and preventing a crash likely would have just made it break in another way.

**Closed by AzeTheGreat** 2022-03-06 23:42 UTC
