### ISSUE TITLE
better info cards;  Index was out of range

### ISSUE THREAD

**Issue by gorkem2020** [AzeTheGreat/ONI-Mods#11] opened 2021-01-25 16:03 UTC
Hello,

I've been getting an error and it crashes. it started happening about a month ago. here are the details;

ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <9577ac7a62ef43179789031239ba8798>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <9577ac7a62ef43179789031239ba8798>:0)
BetterInfoCards.InfoCard.<GetTextOverrides>g__GetResult|20_0 (System.Collections.Generic.List`1[T] cards, BetterInfoCards.InfoCard card, System.Int32 i) (at <e85df6d8c6e64e709f38ff29532e4b40>:0)
BetterInfoCards.InfoCard+<>c__DisplayClass20_0.<GetTextOverrides>b__1 (BetterInfoCards.InfoCard x) (at <e85df6d8c6e64e709f38ff29532e4b40>:0)
System.Linq.Enumerable+SelectListIterator`2[TSource,TResult].ToList () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
BetterInfoCards.InfoCard.GetTextOverrides (System.Collections.Generic.List`1[T] cards) (at <e85df6d8c6e64e709f38ff29532e4b40>:0)
BetterInfoCards.DisplayCard..ctor (System.Collections.Generic.List`1[T] infoCards) (at <e85df6d8c6e64e709f38ff29532e4b40>:0)
BetterInfoCards.DisplayCards.UpdateData (System.Collections.Generic.List`1[T] infoCards) (at <e85df6d8c6e64e709f38ff29532e4b40>:0)
BetterInfoCards.CollectHoverInfo+EditWidgets_Patch.Postfix () (at <e85df6d8c6e64e709f38ff29532e4b40>:0)
(wrapper dynamic-method) HoverTextDrawer.EndDrawing_Patch1(object)
(wrapper dynamic-method) SelectToolHoverTextCard.UpdateHoverElements_Patch0(object,System.Collections.Generic.List`1<KSelectable>)
InterfaceTool.UpdateHoverElements (System.Collections.Generic.List`1[T] hits) (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)
InterfaceTool.LateUpdate () (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)

**Comment by gorkem2020** [comment] 2021-01-25 16:04
[Player.log](https://github.com/AzeTheGreat/ONI-Mods/files/5867790/Player.log)

**Comment by AzeTheGreat** [comment] 2021-02-09 06:22
I'm going to close this as a duplicate since the same issue was reported in #10 and they provided a reproducible save.  I'm struggling to pin down the cause of the issue, but I'll release a fix as soon as I can.

**Closed by AzeTheGreat** 2021-02-09 06:22 UTC
