### ISSUE TITLE
CTD When Clicking on Plug Slug, BetterInfoCards is flagged as issue

### ISSUE THREAD

**Issue by 1samadams** [AzeTheGreat/ONI-Mods#44] opened 2024-09-16 06:46 UTC
NullReferenceException: Object reference not set to an instance of an object

TUNING.CREATURES+EGG_CHANCE_MODIFIERS+<>c__DisplayClass3_0.<CreateElementCreatureModifier>b__1 (System.String descStr) (at <ade4ebd17f71495b9476a7e52f977fe6>:0)
Klei.AI.FertilityModifier.GetTooltip () (at <ade4ebd17f71495b9476a7e52f977fe6>:0)
SimpleInfoScreen.RefreshFertilityPanel (CollapsibleDetailContentPanel targetPanel, UnityEngine.GameObject targetEntity) (at <ade4ebd17f71495b9476a7e52f977fe6>:0)
SimpleInfoScreen.Refresh (System.Boolean force) (at <ade4ebd17f71495b9476a7e52f977fe6>:0)
SimpleInfoScreen.OnSelectTarget (UnityEngine.GameObject target) (at <ade4ebd17f71495b9476a7e52f977fe6>:0)
TargetPanel.SetTarget (UnityEngine.GameObject target) (at <ade4ebd17f71495b9476a7e52f977fe6>:0)
DetailTabHeader.ChangeTab (System.String id) (at <ade4ebd17f71495b9476a7e52f977fe6>:0)
DetailTabHeader.RefreshTabDisplayForTarget (UnityEngine.GameObject target) (at <ade4ebd17f71495b9476a7e52f977fe6>:0)
DetailsScreen.Refresh (UnityEngine.GameObject go) (at <ade4ebd17f71495b9476a7e52f977fe6>:0)
RootMenu.Refresh () (at <ade4ebd17f71495b9476a7e52f977fe6>:0)
RootMenu.OnSelectObject (System.Object data) (at <ade4ebd17f71495b9476a7e52f977fe6>:0)
EventSystem.Trigger (UnityEngine.GameObject go, System.Int32 hash, System.Object data) (at <42a58da1d7eb4994b452d944564c213e>:0)
KMonoBehaviour.Trigger (System.Int32 hash, System.Object data) (at <42a58da1d7eb4994b452d944564c213e>:0)
(wrapper dynamic-method) SelectTool.SelectTool.Select_Patch1(SelectTool,KSelectable,bool)
SelectTool.OnLeftClickDown (UnityEngine.Vector3 cursor_pos) (at <ade4ebd17f71495b9476a7e52f977fe6>:0)
PlayerController.OnKeyDown (KButtonEvent e) (at <ade4ebd17f71495b9476a7e52f977fe6>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <42a58da1d7eb4994b452d944564c213e>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <42a58da1d7eb4994b452d944564c213e>:0)
KInputHandler.HandleEvent (KInputEvent e) (at <42a58da1d7eb4994b452d944564c213e>:0)
KInputController.Dispatch () (at <42a58da1d7eb4994b452d944564c213e>:0)
KInputManager.Dispatch () (at <42a58da1d7eb4994b452d944564c213e>:0)
KInputManager.Update () (at <42a58da1d7eb4994b452d944564c213e>:0)
GameInputManager.Update () (at <42a58da1d7eb4994b452d944564c213e>:0)
Global.Update () (at <ade4ebd17f71495b9476a7e52f977fe6>:0)

Build: U52-626616-SCD

**Comment by AzeTheGreat** [comment] 2024-11-26 03:52
Can you reproduce this?  I cannot.  Please provide a full log if you can.

This looks like another mod is crashing, not Better Info Cards.

**Comment by AzeTheGreat** [comment] 2024-12-11 21:26
Please open a new issue with a full log if this crops up again.  Closing as not reproducible.  My guess is this is another mod's fault.

**Closed by AzeTheGreat** 2024-12-11 21:26 UTC
