### ISSUE TITLE
Better info card not compatible with Fast Track mod

### ISSUE THREAD

**Issue by VitaminC603** [AzeTheGreat/ONI-Mods#36] opened 2023-10-09 00:18 UTC
When enabled with fast track mod, player cannot switch between overlaping objects and buildings in a single block by repeatedly clicking on them.  Disabling either Fast Track or Better Info Card fixes this problem

**Comment by AzeTheGreat** [comment] 2023-10-10 01:13
I'm not able to reproduce this.  Is it with all objects/buildings?  Everything I'm testing is working as expected.

**Comment by AzeTheGreat** [comment] 2023-11-23 15:21
Without additional details, I'm going to close this.  Fast Track touches a lot of code and I'm going to assume it was temporarily partially broken - all of my testing appears to work  fine.   If you have more details, feel free to leave a comment.

**Closed by AzeTheGreat** 2023-11-23 15:21 UTC
